//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TagCloud.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TagCloud.Core.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a
        ///about
        ///across
        ///after
        ///afterwards
        ///again
        ///against
        ///all
        ///almost
        ///alone
        ///along
        ///already
        ///also
        ///although
        ///among
        ///amongst
        ///amoungst
        ///amount
        ///and
        ///another
        ///any
        ///anyhow
        ///anyone
        ///anything
        ///anyway
        ///around
        ///as
        ///at
        ///back
        ///be
        ///because
        ///become
        ///becoming
        ///before
        ///beforehand
        ///behind
        ///being
        ///below
        ///beside
        ///besides
        ///between
        ///both
        ///bottom
        ///but
        ///by
        ///call
        ///cannot
        ///cant
        ///co
        ///computer
        ///con
        ///could
        ///couldnt
        ///cry
        ///de
        ///describe
        ///down
        ///due
        ///during
        ///each
        ///eg
        ///eight
        ///either
        ///eleven
        ///else
        ///elsewhere
        ///empty
        ///enough
        ///etc
        ///even
        ///ever
        ///e [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string en_US_stop {
            get {
                return ResourceManager.GetString("en_US_stop", resourceCulture);
            }
        }
    }
}
